language: node_js

node_js:
  - "9.11.2"

services:
  - mongodb
  - redis-server

cache:
  directories:
    - node_modules
    - $HOME/.npm

jobs:
  include:
    - stage: deploy
      if: branch = master
      install: yarn install
      script: yarn deploy -h https://captain.sv.ufabcnext.com -a api -p $PASSWORD -b master