language: node_js

services:
  - mongodb
  - redis

jobs:
  include:
    - stage: test
      before_install: cd app
      install: yarn install
      script: yarn test
      after_script: cd ../
    - stage: deploy_test
      if: branch = master