language: node_js

node_js:
  - "9.11.2"

services:
  - mongodb
  - redis-server

jobs:
  include:
    - stage: test
      before_install: cd app
      install: yarn install
      script: yarn test
      after_script: cd ../
    - stage: deploy_test
      if: branch = master